variables:
- group: AWSSecrets

steps:
- script: |
    aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    aws configure set region us-east-1
    aws s3 ls
  displayName: 'Access AWS S3'
